/*
 * Generated by https://texteditor.com/multiline-text-art/
 * Style: Blurred Black 
 */
export default `
░█▀▀█ ░█─░█ ░█──░█ ░█▀▀▀█ ▀▀█▀▀
░█─▄▄ ░█─░█ ░█▄▄▄█ ░█──░█ ─░█──
░█▄▄█ ─▀▄▄▀ ──░█── ░█▄▄▄█ ─░█──
`
